// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aula01DB.Model
{
    public partial class Aluno
    {
        public Aluno()
        {
            TurmaAluno = new HashSet<TurmaAluno>();
        }

        public string Matricula { get; set; }
        public string Nome { get; set; }

        public virtual ICollection<TurmaAluno> TurmaAluno { get; set; }
    }
}