// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Aula01DB.Model
{
    public partial class FaculdadeContext : DbContext
    {
        public FaculdadeContext()
        {
        }

        public FaculdadeContext(DbContextOptions<FaculdadeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
        public virtual DbSet<TurmaAluno> TurmaAluno { get; set; }
        public virtual DbSet<VwPegahora> VwPegahora { get; set; }
        public virtual DbSet<VwTurmaAluno> VwTurmaAluno { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-BLN5SEH\\SQLEXPRESS;Initial Catalog=Faculdade;Persist Security Info=True;User ID=sa;Password=sa12345");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<Aluno>(entity =>
            {
                entity.HasKey(e => e.Matricula)
                    .HasName("PK_ALUNO");

                entity.Property(e => e.Matricula)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Curso>(entity =>
            {
                entity.HasKey(e => e.CodigoCurso);

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Turma>(entity =>
            {
                entity.HasKey(e => e.CodigoTurma);

                entity.HasOne(d => d.CodigoCursoNavigation)
                    .WithMany(p => p.Turma)
                    .HasForeignKey(d => d.CodigoCurso)
                    .HasConstraintName("FK_Turma_Curso");
            });

            modelBuilder.Entity<TurmaAluno>(entity =>
            {
                entity.HasKey(e => new { e.CodigoTurma, e.MatriculaAluno });

                entity.Property(e => e.MatriculaAluno)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.DataEntrada).HasColumnType("datetime");

                entity.HasOne(d => d.CodigoTurmaNavigation)
                    .WithMany(p => p.TurmaAluno)
                    .HasForeignKey(d => d.CodigoTurma)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TurmaAluno_Turma");

                entity.HasOne(d => d.MatriculaAlunoNavigation)
                    .WithMany(p => p.TurmaAluno)
                    .HasForeignKey(d => d.MatriculaAluno)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TurmaAluno_Aluno");
            });

            modelBuilder.Entity<VwPegahora>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vw_pegahora");

                entity.Property(e => e.Datahora)
                    .HasColumnType("datetime")
                    .HasColumnName("datahora");
            });

            modelBuilder.Entity<VwTurmaAluno>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vw_TurmaAluno");

                entity.Property(e => e.DataEntrada).HasColumnType("datetime");

                entity.Property(e => e.MatriculaAluno)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Nome)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}