// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aula01DB.Model
{
    public partial class Turma
    {
        public Turma()
        {
            TurmaAluno = new HashSet<TurmaAluno>();
        }

        public int CodigoTurma { get; set; }
        public int? CodigoCurso { get; set; }
        public int? Semestre { get; set; }
        public int? Ano { get; set; }

        public virtual Curso CodigoCursoNavigation { get; set; }
        public virtual ICollection<TurmaAluno> TurmaAluno { get; set; }
    }
}