// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aula01DB.Model
{
    public partial class VwPegahora
    {
        public DateTime Datahora { get; set; }
    }
}