// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Aula01DB.Model
{
    public partial class VwTurmaAluno
    {
        public int CodigoTurma { get; set; }
        public string MatriculaAluno { get; set; }
        public DateTime? DataEntrada { get; set; }
        public string Nome { get; set; }
    }
}